# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportToMapInfo
                                 A QGIS plugin
 плагин экспортирует векторный слой в формат .tab
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Shelipov A.A.
        email                : horusadeptus@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportToMapInfo class from file ExportToMapInfo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_map_info import ExportToMapInfo
    return ExportToMapInfo(iface)
